apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-elasticsearch-config
data:
  elasticsearch.yml: |
    # single-node 운영, 보안 비활성화
    discovery.type: single-node
    xpack.security.enabled: false

