apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-elasticsearch
  labels:
    app: efk
    component: elasticsearch
spec:
  type: {{ .Values.service.type }}
  selector:
    app: efk
    component: elasticsearch
  ports:
  - name: http
    port: {{ .Values.service.elasticsearch.port }}
    targetPort: http
    nodePort: {{ .Values.service.elasticsearch.nodePort }}

