apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-fluentbit-config
  labels:
    app: efk
    component: fluentbit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name           tail
        Path           /var/log/containers/*.log
        Parser         docker
        Tag            kube.*
        Mem_Buf_Limit  5MB
        Skip_Long_Lines On

    [FILTER]
        Name   kubernetes
        Match  kube.*

    [OUTPUT]
        Name  es
        Match *
        Host  {{ .Values.fluentbit.backend.host }}
        Port  {{ .Values.fluentbit.backend.port }}
        Index {{ .Values.fluentbit.backend.index }}

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L


