apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kibana
  labels:
    app: efk
    component: kibana
spec:
  type: {{ .Values.service.type }}
  selector:
    app: efk
    component: kibana
  ports:
  - name: http
    port: {{ .Values.service.kibana.port }}
    targetPort: http
    nodePort: {{ .Values.service.kibana.nodePort }}

