apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kibana-config
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://{{ .Release.Name }}-elasticsearch:{{ .Values.service.elasticsearch.port }}"]
    xpack.security.enabled: false

